name: 'ideological-frontend'

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    container_name: ideological-app-frontend
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - "3000:80"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PUBLIC_URL=.
      - REACT_APP_YANDEX_MAPS_API_KEY=${REACT_APP_YANDEX_MAPS_API_KEY}
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}